import { Footer } from "@/components/Footer";
import "./fonts.css";
import "./globals.sass";
import { Unbounded } from "next/font/google";
import { Header } from "@/components/Header";
import { HeaderMobile } from "@/components/HeaderMobile";

const unbounded = Unbounded({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={unbounded.className}>
        <Header />
        <HeaderMobile />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
